/****************************************************\
 
 Utility
 (A place to store constants and load images)
 
 \****************************************************/
PImage starfield;

PShape sun;
PShape num3Planet;
PShape transitionPlanet;
PImage suntex;
PShape FlameBall;
PShape planet1;
PImage surftex1;
PImage cloudtex;

PShape planet2;
PImage surftex2;
//////////////////////////////////////////////
PImage Cursor;
PImage Player0;
PImage Player1;
PImage playerSide;
PImage playerDSide;
PImage playerFRSide;
PImage playerHSide;
PImage playerS;
PImage playerD;
PImage playerFR;
PImage playerH;
PImage companion;
PImage companionS;
PImage companionD;
PImage companionDS;
PImage blueShot;
PImage redSquare;
PImage redShot;
PImage plasmaShot;
PImage orangeShot;
PImage defaultImage;
PImage title;
PImage subtitle;
PImage titleBackground;
PImage Pause;
PImage pauseInfo;
PImage titleinstruction;
PImage titleinstruction2;
PImage InfoBackground;
PImage travelBackground;
PImage lostInSpaceBackground;
PImage lavaTexture;
PImage fireTexture;
PImage Lvl1Enemy1;
PImage Lives;
PImage LEVEL;
PImage WORLD;
PImage worldClear;
PFont font;
PImage healthBar;
PImage GameOver;
PImage forceField;
PImage backShip;
PImage GetReady;
PImage GO;
PImage LASTLIFE;
PImage redLaser;
PImage playerMissle;
PImage dragonBreath;
PImage planetOne;
PImage planetTwo;
PImage planetThree;
PImage planetFour;
PImage blackLaser;
PImage oneUP;
PImage singleOption;
PImage multiOption;
PImage survivalOption;
PImage flameBall;
PImage ChargeBall;
PImage gameClear;
PImage thankYou;
PImage congrats;
PImage madeBy;
PImage specialThanks;
PImage Bomb;
PImage BombProjectile;
PImage mainGame;
PImage survivalSingleOption;
PImage survivalMultiOption;
/////////////////////////Shop\\\\\\\\\\\\\\\\\\\\\\\\
PImage Credits;
PImage Locked;
PImage Shop;
PImage homingOrbs;
PImage fireRateIncrease;
PImage damageIncrease;
PImage quadShot;
PImage shields;
PImage shieldRegen;
PImage CompanionShop;
PImage shopBackground;
PImage buyShields;
PImage hoverMouse;
//******************Level 1*******************\\
PImage Striker;
PImage Phaser;
PImage Leacher;
PImage DeathSeeker;
PImage Lvl1_boss;
//******************Level 2********************\\
PImage Reaper;
PImage Reaper2;
PImage Kamikazi;
PImage Lvl2_boss;
//******************Level 3********************\\
PImage Ghast;
PImage PyroSkull;
PImage fireCharger;
PImage ultaBossHead;
PImage ultaBossBody;
PImage enemyHomingBall;
// Player constants
final static int   PLAYER_COOLDOWN = 10;
final static float PLAYER_SPEED = 8;
final static float PLAYER_SHOT_SPEED = 8;
static int PLAYER_SHOT_DAMAGE = 8;
final static float playerMissleDamage=5;
float healthBarWidth=500;
float healthBarX=25;
float cHealthBarX;//in setup
float cHealthBarX2=width-300;
float healthBarY=25;
float cHealthBarY=25;
float blah=width-500;
float healthBarHeight=17;
float playerMaxHealth= 100;
//float curHealth = 100;  Already implemented
// Evil Square and Red Shot Constants
final static float RED_SHOT_SPEED = 10;
final static float dragonbreathSpeed=15;
final static float RED_SHOT_DAMAGE = 1;
final static float plasmaShotDamage = 4;
final static float blackLaserDamage= 8;
final static float flameBallDamage=10;
final static float plasmaShotSpeed= 4;
final static float orangeShotDamage=7;
final static float redLaserDamage= 5;
final static float dragonBreathDamage=15;
final static int   EVIL_SQUARE_COOLDOWN = 60;
final static float EVIL_SQUARE_X_SPEED = 0;
final static float EVIL_SQUARE_Y_SPEED = 4;
final float boomScale= .25;
final int boomDuration=20;
final int boomAmount=10;
final int boomSplit=2;
final int boomMinSize=5;

////////////////////////////////////Shop COST\\\\\\\\\\\\\\\\\\\\\\\\\\\\
final static int homingCost=350;
final static int fireRateCost=50;
final static int quadShotCost=150;
static int damageCost=250;
final static int shieldsCost=350;
final static int shieldRegenCost=400;
final static int shieldRegen2Cost=450;
static int companionCost=500; 
public void loadImages()
{
  suntex = loadImage("planet1.jpg");  
  /////////////////////////////////////////////////////////
  backShip=loadImage("backShip.png");
  Player0 = loadImage("original_player.png");
  blueShot = loadImage("blue_shot.png");
  redSquare = loadImage("red_square.png");
  redShot = loadImage("red_shot.png");
  orangeShot= loadImage("orangeLaser.png");
  Striker= loadImage("enemy_1(top Bottom).png");
  Phaser= loadImage("enemy_2(top Bottom).png");
  defaultImage = loadImage("default_image.png");
  title =loadImage("TITLE.PNG");
  subtitle= loadImage("Subtitle.png");
  LEVEL= loadImage("Level.png");
  titleBackground=loadImage("titlebackground.jpg");
  Pause= loadImage("Pause.png");
  pauseInfo= loadImage("pauseInfo.png");
  titleinstruction= loadImage("titleinstruction.png");
  titleinstruction2= loadImage("titleinstruction2.png");
  Lives= loadImage("Lives.png");
  healthBar= loadImage("Healthbar.png");
  GameOver= loadImage("GameOver.png");
  forceField=loadImage("forcefield.png");
  plasmaShot = loadImage("energyBall.png");
  GetReady = loadImage("GetReady.png");
  GO= loadImage("GO!!!!.PNG");
  LASTLIFE= loadImage("LASTLIFE.png");
  InfoBackground= loadImage("InfoBackground.jpg");
  travelBackground=loadImage("travelBackground.png");
  lostInSpaceBackground=loadImage("lostSpaceBackground.jpg");
  Leacher= loadImage("enemy_3(Side Attack).png");
  DeathSeeker=loadImage("enemy_4(Side Attack).png");
  redLaser= loadImage("redLaser.png");
  Lvl1_boss= loadImage("ddragon_FINAL.png");
  dragonBreath= loadImage("DragonBreath.png");
  playerMissle= loadImage("homingBall.png");
  planetOne= loadImage("planet1.png");
  planetTwo= loadImage("planet2.png");
  planetThree= loadImage("planet3.png");
  planetFour= loadImage("planet4.png");
  WORLD= loadImage("World.png");
  worldClear = loadImage("WorldClear.png");
  Reaper = loadImage("stealth_ship.png");
  Kamikazi= loadImage("kamikazi.png");
  blackLaser= loadImage("blackLaser.png");
  Lvl2_boss= loadImage("second_boss_v2.png");
  playerSide= loadImage("original_player(side scroller).png");
  Credits= loadImage("Credits.png");
  Shop=loadImage("SHOP.PNG");
  homingOrbs= loadImage("HomingOrbs.png");
  fireRateIncrease=loadImage("fireRateIncrease.png");
  damageIncrease=loadImage("damageIncrease.png");
  quadShot= loadImage("QuadShot.png");
  Player1=loadImage("original_player(damage).png");
  playerDSide=loadImage("original_player(damage&SideScroller).png");
  playerFRSide=loadImage("original_player(blue tubes&SideScroller).png");
  playerHSide=loadImage("original_player(homing&SideScroller).png");
  playerH=loadImage("original_player(homing).png");
  playerD=loadImage("original_player(damage).png");
  playerFR=loadImage("original_player(blue tubes).png");
  shields= loadImage("shields.png");
  shieldRegen=loadImage("shieldRegen.png");
  Locked=loadImage("Locked.png");
  companion=loadImage("companion.png");
  companionS=loadImage("companion(side scroller).png");
  companionD=loadImage("companion_damage.png");
  companionDS=loadImage("companion_damage(side scroller).png");
  CompanionShop=loadImage("Companionshop.png");
  oneUP=loadImage("1-up.png");
  singleOption=loadImage("singleplayerOption.png");
  multiOption=loadImage("multiplayerOption.png");
  survivalOption=loadImage("survivalOption.png");
  Ghast= loadImage("level_3_enemy.png");
  lavaTexture= loadImage("lavaTexture.jpg");
  fireTexture= loadImage("fireTexture.jpg");
  flameBall=loadImage("FlameBreath.png");
  PyroSkull=loadImage("melting face.png");
  fireCharger=loadImage("pyro ship.png");
  ChargeBall=loadImage("fire_ball.png");
  Reaper2=loadImage("stealth_ship2.png");
  ultaBossHead=loadImage("FINAL_BOSS_HEAD_v2.png");
  ultaBossBody=loadImage("FINAL_BOSSMAN.png");
  gameClear=loadImage("gameClearLogo.png");
  thankYou=loadImage("thankyou.png");
  congrats= loadImage("congrats.png");
  madeBy=loadImage("madeBy.png");
  specialThanks=loadImage("specialThanks.png");
  Cursor=loadImage("cursor.png");
  Cursor.resize(50, 50);
  shopBackground=loadImage("shopbackground.jpg");
  buyShields=loadImage("buyShields.png");
  hoverMouse=loadImage("hoverMouse.png");
  Bomb=loadImage("bomb.png");
  BombProjectile=loadImage("bombProjectile.png");
  enemyHomingBall= loadImage("enemyHomingBall.png");
  mainGame=loadImage("mainGameLogo.png");
  survivalSingleOption=loadImage("survivalSingleOption.png");
  survivalMultiOption=loadImage("survivalmultiOption.png");
  //Fonts
  font= loadFont("font.vlw");
}
